import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import Layout from '../components/Layout';
import styles from '../styles/Home.module.css';
import { GetContractInfos, CheckContractIdByAddress } from '../hooks/indexSearch';

const Home: NextPage = () => {
  return (
    <Layout>
      <div className={styles.container}>
        <Head>
          <title>Blockchain-based NFT Copyright Registration System</title>
          <meta content="Generated by @rainbow-me/create-rainbowkit" name="description" />
          <link href="/favicon.ico" rel="icon" />
        </Head>

        <main className={styles.main}>
          <ConnectButton />

          <h3 className={styles.title}>
            Blockchain-based NFT Copyright Registration System
          </h3>

          <h4>
            The copyright number is a unique ID value assigned by the platform.
          </h4>

          <h1 className={styles.description}>
            🔎 Find the copyright number associated with a wallet address
            <CheckContractIdByAddress />
          </h1>

          <h1 className={styles.description}>
            🔎 Retrieve patent information from the blockchain using the copyright number
          </h1>
          <GetContractInfos />

        </main>
        <>
        </>
        <footer className={styles.footer}>
          <a href="https://rainbow.me" rel="noopener noreferrer" target="_blank">
            2024 Eth global reated by Hyunki Cho
          </a>
        </footer>
      </div>
    </Layout>
  );
};

export default Home;
